openapi: "3.0.0"
info:
  title: A simple server to hold secrets
  description: A simple server to hold secrets
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: 0.0.1
servers:
  - url: / 
paths:
  /:
    post:
      operationId: storeSecret
      description: Store a secret for retrieval
      responses:
        '200':
          description: A key
          content:
            application/json:
              schema:
                type: object
                properties:
                  key:
                    description: A key generated for secret retrieval
  /{key}:
    get:
      operationId: getSecret
      description: Get a secret using a key (secret is deleted together with the key upon retrieval)
      parameters:
        - name: key
          in: path
          required: true
          description: The key of the secret to retrieve
          schema:
            type: string
      responses:
        '200':
          description: A secret
          content:
            application/json:
              schema:
                type: object
                properties:
                  secret:
                    description: Secret text
        '404':
          description: The key is not found, maybe it had previously been retrieved